In [407]:
import pandas as pd
import os
from datetime import timezone
import datetime
import time
import math
import copy
import mysql.connector
from mysql.connector import Error
from sqlalchemy import create_engine

In [277]:
MasterData = pd.read_csv('Master_Data_File.csv')
MasterData.set_index('index')

,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume
index,,,,,,,,
0,1444311600,2015-10-08 13:40:00,BTCUSD,0.00,242.50,0.00,242.50,0.050000
1,1444311660,2015-10-08 13:41:00,BTCUSD,242.50,242.95,242.50,242.95,0.001000
2,1444311720,2015-10-08 13:42:00,BTCUSD,242.95,242.95,242.95,242.95,0.000000
3,1444311780,2015-10-08 13:43:00,BTCUSD,242.95,242.96,242.95,242.96,0.010000
4,1444311840,2015-10-08 13:44:00,BTCUSD,242.96,242.96,242.96,242.96,0.033491
...,...,...,...,...,...,...,...,...
3063873,1634428860000,2021-10-17 00:01:00,BTCUSD,60877.53,60877.53,60851.85,60875.98,0.182190
3063874,1634428920000,2021-10-17 00:02:00,BTCUSD,60875.98,60937.30,60854.84,60922.25,1.135391
3063875,1634428980000,2021-10-17 00:03:00,BTCUSD,60922.25,60925.99,60809.75,60809.75,0.108527
3063876,1634429040000,2021-10-17 00:04:00,BTCUSD,60809.75,60829.33,60716.28,60716.28,0.216773
3063877,1634429100000,2021-10-17 00:05:00,BTCUSD,60716.28,60716.28,60712.32,60715.55,0.022586

In [278]:
MasterData = MasterData.iloc[620: , :]
MasterData = MasterData.reset_index(drop=True)
del MasterData['index']
MasterData

,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume
0,1444348800,2015-10-09 00:00:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
1,1444348860,2015-10-09 00:01:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
2,1444348920,2015-10-09 00:02:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
3,1444348980,2015-10-09 00:03:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
4,1444349040,2015-10-09 00:04:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
...,...,...,...,...,...,...,...,...
3063253,1634428860000,2021-10-17 00:01:00,BTCUSD,60877.53,60877.53,60851.85,60875.98,0.182190
3063254,1634428920000,2021-10-17 00:02:00,BTCUSD,60875.98,60937.30,60854.84,60922.25,1.135391
3063255,1634428980000,2021-10-17 00:03:00,BTCUSD,60922.25,60925.99,60809.75,60809.75,0.108527
3063256,1634429040000,2021-10-17 00:04:00,BTCUSD,60809.75,60829.33,60716.28,60716.28,0.216773
3063257,1634429100000,2021-10-17 00:05:00,BTCUSD,60716.28,60716.28,60712.32,60715.55,0.022586

In [279]:
# temp_set = MasterData[0:10]
for i in range(len(MasterData)):
    u_timestamp = MasterData.loc[i,'Unix Timestamp']
    u_timestamp_len = int(math.log10(u_timestamp))+1
    if u_timestamp_len > 10 : 
        if u_timestamp_len ==13:
            MasterData.loc[i,'Unix Timestamp']= u_timestamp/1000
        elif u_timestamp_len ==12:
            MasterData.loc[i,'Unix Timestamp']= u_timestamp/100
        elif u_timestamp_len ==14:
            MasterData.loc[i,'Unix Timestamp']= u_timestamp/10000
        elif u_timestamp_len ==11:
            MasterData.loc[i,'Unix Timestamp']= u_timestamp/10
        elif u_timestamp_len ==15:
            MasterData.loc[i,'Unix Timestamp']= u_timestamp/100000
            
    if(i%100000==0):
        print(i)
MasterData

0
100000
200000
300000
400000
500000
600000
700000
800000
900000
1000000
1100000
1200000
1300000
1400000
1500000
1600000
1700000
1800000
1900000
2000000
2100000
2200000
2300000
2400000
2500000
2600000
2700000
2800000
2900000
3000000

,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume
0,1.444349e+09,2015-10-09 00:00:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
1,1.444349e+09,2015-10-09 00:01:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
2,1.444349e+09,2015-10-09 00:02:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
3,1.444349e+09,2015-10-09 00:03:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
4,1.444349e+09,2015-10-09 00:04:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
...,...,...,...,...,...,...,...,...
3063253,1.634429e+09,2021-10-17 00:01:00,BTCUSD,60877.53,60877.53,60851.85,60875.98,0.182190
3063254,1.634429e+09,2021-10-17 00:02:00,BTCUSD,60875.98,60937.30,60854.84,60922.25,1.135391
3063255,1.634429e+09,2021-10-17 00:03:00,BTCUSD,60922.25,60925.99,60809.75,60809.75,0.108527
3063256,1.634429e+09,2021-10-17 00:04:00,BTCUSD,60809.75,60829.33,60716.28,60716.28,0.216773
3063257,1.634429e+09,2021-10-17 00:05:00,BTCUSD,60716.28,60716.28,60712.32,60715.55,0.022586

In [285]:
MasterData.to_csv('Master_Data_File.csv', index=False)

In [130]:
# combine All Files into 1 
rootDir = '../data1'
master_fname= 'Master_Data_File2.csv'
file_dict={}
years= []

for dirName, subdirList, fileList in os.walk(rootDir):
    if (dirName == rootDir):
        print('In directory: %s' % dirName)
        for fname in fileList:
            split = fname.split('_')
            if (len(split)>3):
                print('\t Loading  '+fname)
                years.append(split[2])
                file_dict[split[2]]= fname

years.sort()
years.reverse()

data_files = []
for year in years: 
    file_path = os.path.join(rootDir, file_dict[year])
    tempdata = pd.read_csv(file_path, skiprows=1)
    data_files.append(tempdata)
    
master_data_file1 = pd.concat(data_files,ignore_index=True)
master_data_file1 = master_data_file1.sort_index(axis=0 ,ascending=False)
master_data_file1 = master_data_file1.reset_index(drop=True)

# master_data_file1.to_csv(master_fname, index=False)

print('done')
master_data_file1

In directory: ../data1
	 Loading  Bitstamp_BTCUSD_2017_minute.csv
	 Loading  Bitstamp_BTCUSD_2020_minute.csv
	 Loading  Bitstamp_BTCUSD_2018_minute.csv
	 Loading  Bitstamp_BTCUSD_2021_minute.csv
	 Loading  Bitstamp_BTCUSD_2019_minute.csv
done

,unix,date,symbol,open,high,low,close,Volume BTC,Volume USD
0,1483228860,2017-01-01 00:01:00,BTC/USD,966.34,966.34,966.34,966.34,7.610000,7353.847400
1,1483228920,2017-01-01 00:02:00,BTC/USD,966.16,966.37,966.16,966.37,8.087376,7815.397864
2,1483228980,2017-01-01 00:03:00,BTC/USD,966.37,966.37,966.37,966.37,0.000000,0.000000
3,1483229040,2017-01-01 00:04:00,BTC/USD,966.37,966.37,966.37,966.37,0.000000,0.000000
4,1483229100,2017-01-01 00:05:00,BTC/USD,966.43,966.43,966.43,966.43,0.107000,103.408010
...,...,...,...,...,...,...,...,...,...
2514230,1636441920,2021-11-09 07:12:00,BTC/USD,68061.04,68061.04,68032.54,68032.54,0.081494,5544.232930
2514231,1636441980,2021-11-09 07:13:00,BTC/USD,68050.04,68064.52,68022.27,68064.52,0.057895,3940.565437
2514232,1636442040,2021-11-09 07:14:00,BTC/USD,68062.18,68062.18,68043.15,68043.15,5.407671,367954.959478
2514233,1636442100,2021-11-09 07:15:00,BTC/USD,68043.68,68106.81,68043.15,68095.83,1.902294,129538.316072
2514234,1636442160,2021-11-09 07:16:00,BTC/USD,68104.10,68122.09,68103.30,68103.30,0.098000,6674.123400

In [131]:
# deletes first entry to start at 0:00:00
master_data_file1 = master_data_file1.iloc[1439: , :]

master_data_file1 = master_data_file1.reset_index(drop=True)
del master_data_file1['Volume USD']
master_data_file1

,unix,date,symbol,open,high,low,close,Volume BTC
0,1483315200,2017-01-02 00:00:00,BTC/USD,997.75,997.80,997.75,997.80,9.218044
1,1483315260,2017-01-02 00:01:00,BTC/USD,997.80,999.76,997.80,999.76,16.163329
2,1483315320,2017-01-02 00:02:00,BTC/USD,999.76,999.89,999.76,999.89,0.806480
3,1483315380,2017-01-02 00:03:00,BTC/USD,999.89,999.89,999.89,999.89,0.000000
4,1483315440,2017-01-02 00:04:00,BTC/USD,997.89,997.89,996.89,996.89,0.722813
...,...,...,...,...,...,...,...,...
2512791,1636441920,2021-11-09 07:12:00,BTC/USD,68061.04,68061.04,68032.54,68032.54,0.081494
2512792,1636441980,2021-11-09 07:13:00,BTC/USD,68050.04,68064.52,68022.27,68064.52,0.057895
2512793,1636442040,2021-11-09 07:14:00,BTC/USD,68062.18,68062.18,68043.15,68043.15,5.407671
2512794,1636442100,2021-11-09 07:15:00,BTC/USD,68043.68,68106.81,68043.15,68095.83,1.902294
2512795,1636442160,2021-11-09 07:16:00,BTC/USD,68104.10,68122.09,68103.30,68103.30,0.098000

In [132]:
master_data_file1=master_data_file1.rename(columns={"unix": "Unix Timestamp", "date": "Date",'symbol':'Symbol','open':'Open','high':'High','low':'Low','close':'Close','Volume BTC':'Volume'})
master_data_file1

,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume
0,1483315200,2017-01-02 00:00:00,BTC/USD,997.75,997.80,997.75,997.80,9.218044
1,1483315260,2017-01-02 00:01:00,BTC/USD,997.80,999.76,997.80,999.76,16.163329
2,1483315320,2017-01-02 00:02:00,BTC/USD,999.76,999.89,999.76,999.89,0.806480
3,1483315380,2017-01-02 00:03:00,BTC/USD,999.89,999.89,999.89,999.89,0.000000
4,1483315440,2017-01-02 00:04:00,BTC/USD,997.89,997.89,996.89,996.89,0.722813
...,...,...,...,...,...,...,...,...
2512791,1636441920,2021-11-09 07:12:00,BTC/USD,68061.04,68061.04,68032.54,68032.54,0.081494
2512792,1636441980,2021-11-09 07:13:00,BTC/USD,68050.04,68064.52,68022.27,68064.52,0.057895
2512793,1636442040,2021-11-09 07:14:00,BTC/USD,68062.18,68062.18,68043.15,68043.15,5.407671
2512794,1636442100,2021-11-09 07:15:00,BTC/USD,68043.68,68106.81,68043.15,68095.83,1.902294
2512795,1636442160,2021-11-09 07:16:00,BTC/USD,68104.10,68122.09,68103.30,68103.30,0.098000

In [403]:
def get_missing_days(date_one,date_two,data_file_1,data_file_2):
    missing_days = []
#     add first date to new data set 
    timestamp = date_one.replace(tzinfo=timezone.utc).timestamp()
    first_date_df  = data_file_1.loc[data_file_1['Unix Timestamp'] == timestamp]
    first_date_row = first_date_df.values.tolist()
    missing_days.append(first_date_row[0])
#     Loop Control
    difference = date_two-date_one
    loop_num = int(difference.total_seconds() / 60.0)
#     add missing dates
    for x in range(loop_num-1):
        new_date  =  date_one + datetime.timedelta(minutes=1+x)
        timestamp = new_date.replace(tzinfo=timezone.utc).timestamp()
        temp_data_row_df  = data_file_2.loc[data_file_2['Unix Timestamp'] == timestamp]
        if (len(temp_data_row_df)>0):
            new_data_row = temp_data_row_df.values.tolist()
            missing_days.append(new_data_row[0])
        else: 
#             use the last dates values and new unix and date. 
            last_item_values    = copy.copy(first_date_row[0])
            last_item_values[0] = timestamp
            last_item_values[1] = new_date.strftime('%Y-%m-%d %H:%M:%S')
            missing_days.append(last_item_values)
            
#   add last date 
    timestamp = date_two.replace(tzinfo=timezone.utc).timestamp()
    second_date_df  = data_file_1.loc[data_file_1['Unix Timestamp'] == timestamp]
    second_date_row = second_date_df.values.tolist()
    missing_days.append(second_date_row[0])
    return missing_days


last_date
fixed_data_set=[]
# temp_set = MasterData.iloc[2500000:2600000]
# temp_set = temp_set.reset_index(drop=True)
for i in range(len(MasterData)) :
    date = datetime.datetime.utcfromtimestamp(MasterData.loc[i,'Unix Timestamp'])
    if i !=0:
        difference = date-last_date
        if (difference.total_seconds() / 60.0 >1):
#             add missing items to new data set
            missing_list = get_missing_days(last_date,date,MasterData,master_data_file1)
            for x in missing_list:
                fixed_data_set.append(x)
            print('Difference: ', difference.total_seconds() / 60.0)
        else:
#         add item to new data set
            data_row = MasterData.loc[i].values.tolist()
            fixed_data_set.append(data_row)
    else: 
#         add first item to new data set
        data_row = MasterData.loc[i].values.tolist()
        fixed_data_set.append(data_row)
        
    last_date=date
    
# for x in fixed_data_set:
#     print(x)

print('done')

Difference:  3766.0
Difference:  66.0
Difference:  31664.0
Difference:  540.0
Difference:  2.0
Difference:  1440.0
Difference:  2.0
Difference:  2.0
Difference:  1441.0
Difference:  1441.0
Difference:  3.0
Difference:  1440.0
Difference:  866.0
Difference:  1441.0
Difference:  1441.0
Difference:  1441.0
Difference:  1441.0
Difference:  11577.0
Difference:  1440.0
Difference:  1441.0
Difference:  1441.0
Difference:  2881.0
Difference:  1440.0
Difference:  1440.0
Difference:  1440.0
Difference:  1440.0
Difference:  1439.0
Difference:  1440.0
Difference:  1440.0
Difference:  1439.0
Difference:  1441.0
Difference:  1440.0
Difference:  2.0
Difference:  1439.0
Difference:  1440.0
Difference:  1440.0
Difference:  1440.0
Difference:  1440.0
Difference:  1440.0
Difference:  1440.0
Difference:  1439.0
Difference:  1439.0
Difference:  1440.0
Difference:  1440.0
Difference:  1439.0
Difference:  2.0
Difference:  1440.0
Difference:  2.0
Difference:  2.0
Difference:  2.0
Difference:  1440.0
Difference:  1440.0
Difference:  2.0
Difference:  2.0
Difference:  3.0
Difference:  2.0
Difference:  2.0
Difference:  2.0
Difference:  2.0
Difference:  3.0
Difference:  2.0
Difference:  3.0
Difference:  5.0
Difference:  6.0
Difference:  2.0
Difference:  4.0
Difference:  3.0
Difference:  2.0
Difference:  5.0
Difference:  3.0
Difference:  2.0
Difference:  3.0
Difference:  3.0
Difference:  4.0
Difference:  5.0
Difference:  4.0
Difference:  3.0
Difference:  3.0
Difference:  2.0
Difference:  2.0
Difference:  3.0
Difference:  1440.0
Difference:  2.0
Difference:  2.0
Difference:  5.0
Difference:  7.0
Difference:  7.0
Difference:  6.0
Difference:  6.0
Difference:  6.0
Difference:  6.0
Difference:  5.0
Difference:  6.0
Difference:  5.0
Difference:  6.0
Difference:  6.0
Difference:  2.0
Difference:  6.0
Difference:  5.0
Difference:  10.0
Difference:  2.0
done

In [404]:
df = pd.DataFrame(fixed_data_set, columns =['Unix Timestamp','Date','Symbol','Open','High','Low','Close','Volume']) 
for i in range(len(df)) :
    date = datetime.datetime.utcfromtimestamp(df.loc[i,'Unix Timestamp'])
    if i !=0:
        difference = date-last_date
        if (difference.total_seconds() / 60.0 >1):
            print(df.loc[i])
            print(i,' Difference: ', difference.total_seconds() / 60.0)
    last_date=date

In [405]:
df

,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume
0,1.444349e+09,2015-10-09 00:00:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
1,1.444349e+09,2015-10-09 00:01:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
2,1.444349e+09,2015-10-09 00:02:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
3,1.444349e+09,2015-10-09 00:03:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
4,1.444349e+09,2015-10-09 00:04:00,BTCUSD,243.95,243.95,243.95,243.95,0.000000
...,...,...,...,...,...,...,...,...
3168102,1.634429e+09,2021-10-17 00:01:00,BTCUSD,60877.53,60877.53,60851.85,60875.98,0.182190
3168103,1.634429e+09,2021-10-17 00:02:00,BTCUSD,60875.98,60937.30,60854.84,60922.25,1.135391
3168104,1.634429e+09,2021-10-17 00:03:00,BTCUSD,60922.25,60925.99,60809.75,60809.75,0.108527
3168105,1.634429e+09,2021-10-17 00:04:00,BTCUSD,60809.75,60829.33,60716.28,60716.28,0.216773
3168106,1.634429e+09,2021-10-17 00:05:00,BTCUSD,60716.28,60716.28,60712.32,60715.55,0.022586

In [406]:
df.to_csv('Master_Data_File.csv', index=False)

In [408]:
# for getting ENv vars 
env_vars = {} # or dict {}
with open('env.txt') as f:
    for line in f:
        if line.startswith('#') or not line.strip():
            continue
        key, value = line.strip().split('=', 1)
        env_vars[key]= value
print(env_vars)

{'HOST': '64.20.33.250', 'DB': 'st19945_tickerData', 'USER': 'st19945_tickerData', 'PASSWORD': 'CU2021'}

In [409]:
# create sqlalchemy engine
engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}"
                       .format(user=env_vars['USER'],
                               pw=env_vars['PASSWORD'],
                               host=env_vars['HOST'],
                               db=env_vars['DB']))

In [410]:
################################################
# Do not run unless you are pushing the whole new data to DB 
################################################

df.to_sql('BTC_Ticker_Data', con = engine, if_exists = 'append', chunksize = 1000)

Test code below this line 
************

In [372]:
# 2720216,2723096,2733176
# 2020-12-11 00:02:00
print(df.iloc[2720213])
print(df.iloc[2720214])
print(df.iloc[2720215])
print(df.iloc[2720216])

Unix Timestamp           1607558520.0
Date              2020-12-10 00:02:00
Symbol                         BTCUSD
Open                         18545.63
High                         18562.21
Low                          18538.03
Close                        18562.21
Volume                        0.22294
Name: 2720213, dtype: object
Unix Timestamp           1607558580.0
Date              2020-12-10 00:03:00
Symbol                         BTCUSD
Open                         18562.21
High                         18562.21
Low                          18542.36
Close                        18542.36
Volume                       0.008466
Name: 2720214, dtype: object
Unix Timestamp           1607644920.0
Date              2020-12-11 00:02:00
Symbol                         BTCUSD
Open                         18562.21
High                         18562.21
Low                          18542.36
Close                        18542.36
Volume                       0.008466
Name: 2720215, dtype: object
Unix Timestamp           1607644920.0
Date              2020-12-11 00:02:00
Symbol                         BTCUSD
Open                         18562.21
High                         18562.21
Low                          18542.36
Close                        18542.36
Volume                       0.008466
Name: 2720216, dtype: object

In [363]:
# 1607817780.0

old_date = 1607817660.0
print(old_date)
date = datetime.datetime.utcfromtimestamp(old_date)
print(date)
new_date  =  date + datetime.timedelta(minutes=1)
print(new_date)
timestamp = new_date.replace(tzinfo=timezone.utc).timestamp()
print(timestamp)

old_row_df = MasterData.loc[MasterData['Unix Timestamp'] == old_date]
old_row_list=old_row_df.values[0].tolist()
print(old_row_list)
old_row_list[0]=timestamp
old_row_list[1]=new_date.strftime('%Y-%m-%d %H:%M:%S')
print(old_row_list)
# print(MasterData.loc[MasterData['Unix Timestamp'] == old_date])



# print(df.iloc[2723095])
# print(df.iloc[2723096])

1607817660.0
2020-12-13 00:01:00
2020-12-13 00:02:00
1607817720.0
[1607817660.0, '2020-12-13 00:01:00', 'BTCUSD', 18833.51, 18859.0, 18833.51, 18852.78, 1.09873777]
[1607817720.0, '2020-12-13 00:02:00', 'BTCUSD', 18833.51, 18859.0, 18833.51, 18852.78, 1.09873777]

In [55]:
last_date,last_time = MasterData.loc[1379,'Date'].split(' ')
last_hour,last_mins, last_sec = last_time.split(':') 

date,time = MasterData.loc[1380,'Date'].split(' ')
hour,mins, sec = time.split(':') 
if (mins == '00'):
    if (hour == '00'):
        if (last_hour != '23' and last_mins != 59):
            print('mismatch')
#         last_hour should equal 23 
#         last_mins should equal 59 
#         else: 
#             print("pass 00:00")
    else : 
        if (int(last_hour) != (int(hour)-1) and last_mins != 59):
            print('mismatch')
#         last_hour should equal hour - 1  
#         last_mins should equal 59
#         else: 
#             print("pass *:00")
else: 
    if (int(last_mins) != int(mins)-1):
        print('mismatch')
#         last_mins should equal mins -1 
#     else: 
#         print("pass mins")


print(last_date,last_hour,last_mins, last_sec)
print(date,hour,mins,sec)

pass *:00
2015-10-09 22 59 00
2015-10-09 23 00 00

In [134]:
last_date,last_hour,last_mins,last_sec
for i in range(len(MasterData)) :
    
    date,time = MasterData.loc[i,'Date'].split(' ')
    hour, mins, sec = time.split(':') 
    if i !=0:
        if (mins == '00'):
            if (hour == '00'):
                if (last_hour != '23' and last_mins != 59):
                    print('m',i,' ',last_date,last_hour,last_mins, last_sec)
                    print('-',i,' ',date,hour,mins,sec)
                    last_year,last_month,last_day = last_date.split('-')
                    year,month,day = date.split('-')
                    a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
                    b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
                    c = b-a 
                    print('Difference: ', c)
                    
                    
            else : 
                if (int(last_hour) != (int(hour)-1) and last_mins != 59):
                    print('m',i,' ',last_date,last_hour,last_mins, last_sec)
                    print('-',i,' ',date,hour,mins,sec)
                    last_year,last_month,last_day = last_date.split('-')
                    year,month,day = date.split('-')
                    a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
                    b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
                    c = b-a 
                    print('Difference: ', c)
        else: 
            if (int(last_mins) != int(mins)-1):
                print('m',i,' ',last_date,last_hour,last_mins, last_sec)
                print('-',i,' ',date,hour,mins,sec)
                last_year,last_month,last_day = last_date.split('-')
                year,month,day = date.split('-')
                a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
                b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
                c = b-a 
                print('Difference: ', c)
    last_date=date
    last_hour=hour
    last_mins=mins
    last_sec =sec
#     if i %1000000==0:
#         print('working')
print('done')

m 1510679   2018-08-23 01 58 00
- 1510679   2018-08-25 16 44 00
Difference:  2 days, 14:46:00
m 1512517   2018-08-26 23 21 00
- 1512517   2018-08-27 00 27 00
Difference:  1:06:00
m 1628988   2018-11-15 21 37 00
- 1628988   2018-12-07 21 21 00
Difference:  21 days, 23:44:00
m 1710689   2019-02-02 15 01 00
- 1710689   2019-02-03 00 01 00
Difference:  9:00:00
m 1723649   2019-02-12 00 00 00
- 1723649   2019-02-12 00 02 00
Difference:  0:02:00
m 1727970   2019-02-15 00 02 00
- 1727970   2019-02-16 00 02 00
Difference:  1 day, 0:00:00
m 1743809   2019-02-27 00 00 00
- 1743809   2019-02-27 00 02 00
Difference:  0:02:00
m 1748130   2019-03-02 00 02 00
- 1748130   2019-03-02 00 04 00
Difference:  0:02:00
m 1801410   2019-04-10 00 03 00
- 1801410   2019-04-10 00 06 00
Difference:  0:03:00
m 1804287   2019-04-12 00 02 00
- 1804287   2019-04-13 00 02 00
Difference:  1 day, 0:00:00
m 1823009   2019-04-26 00 03 00
- 1823009   2019-04-26 14 29 00
Difference:  14:26:00
m 1921503   2019-07-08 00 02 00
- 1921503   2019-07-16 00 59 00
Difference:  8 days, 0:57:00
m 1934407   2019-07-25 00 02 00
- 1934407   2019-07-26 00 02 00
Difference:  1 day, 0:00:00
m 2007849   2019-09-19 00 03 00
- 2007849   2019-09-20 00 03 00
Difference:  1 day, 0:00:00
m 2026570   2019-10-03 00 03 00
- 2026570   2019-10-04 00 03 00
Difference:  1 day, 0:00:00
m 2055372   2019-10-24 00 04 00
- 2055372   2019-10-25 00 04 00
Difference:  1 day, 0:00:00
m 2081293   2019-11-12 00 04 00
- 2081293   2019-11-13 00 04 00
Difference:  1 day, 0:00:00
m 2092814   2019-11-21 00 04 00
- 2092814   2019-11-22 00 03 00
Difference:  23:59:00
m 2121615   2019-12-12 00 03 00
- 2121615   2019-12-13 00 03 00
Difference:  1 day, 0:00:00
m 2130256   2019-12-19 00 03 00
- 2130256   2019-12-20 00 03 00
Difference:  1 day, 0:00:00
m 2159056   2020-01-09 00 02 00
- 2159056   2020-01-10 00 01 00
Difference:  23:59:00
m 2196498   2020-02-06 00 02 00
- 2196498   2020-02-07 00 02 00
Difference:  1 day, 0:00:00
m 2213779   2020-02-19 00 02 00
- 2213779   2020-02-19 00 04 00
Difference:  0:02:00
m 2215220   2020-02-20 00 04 00
- 2215220   2020-02-21 00 03 00
Difference:  23:59:00
m 2264178   2020-03-26 00 00 00
- 2264178   2020-03-27 00 00 00
Difference:  1 day, 0:00:00
m 2282899   2020-04-09 00 00 00
- 2282899   2020-04-10 00 00 00
Difference:  1 day, 0:00:00
m 2301620   2020-04-23 00 00 00
- 2301620   2020-04-24 00 00 00
Difference:  1 day, 0:00:00
m 2330421   2020-05-14 00 00 00
- 2330421   2020-05-15 00 00 00
Difference:  1 day, 0:00:00
m 2349142   2020-05-28 00 00 00
- 2349142   2020-05-29 00 00 00
Difference:  1 day, 0:00:00
m 2377943   2020-06-18 00 00 00
- 2377943   2020-06-19 00 00 00
Difference:  1 day, 0:00:00
m 2396665   2020-07-02 00 01 00
- 2396665   2020-07-03 00 00 00
Difference:  23:59:00
m 2415387   2020-07-16 00 01 00
- 2415387   2020-07-17 00 00 00
Difference:  23:59:00
m 2464348   2020-08-20 00 00 00
- 2464348   2020-08-21 00 00 00
Difference:  1 day, 0:00:00
m 2472989   2020-08-27 00 00 00
- 2472989   2020-08-28 00 00 00
Difference:  1 day, 0:00:00
m 2491711   2020-09-10 00 01 00
- 2491711   2020-09-11 00 00 00
Difference:  23:59:00
m 2506112   2020-09-21 00 00 00
- 2506112   2020-09-21 00 02 00
Difference:  0:02:00
m 2510432   2020-09-24 00 01 00
- 2510432   2020-09-25 00 01 00
Difference:  1 day, 0:00:00
m 2516192   2020-09-29 00 00 00
- 2516192   2020-09-29 00 02 00
Difference:  0:02:00
m 2533473   2020-10-11 00 02 00
- 2533473   2020-10-11 00 04 00
Difference:  0:02:00
m 2553631   2020-10-25 00 01 00
- 2553631   2020-10-25 00 03 00
Difference:  0:02:00
m 2579551   2020-11-12 00 02 00
- 2579551   2020-11-13 00 02 00
Difference:  1 day, 0:00:00
m 2618433   2020-12-10 00 03 00
- 2618433   2020-12-11 00 03 00
Difference:  1 day, 0:00:00
m 2621312   2020-12-13 00 01 00
- 2621312   2020-12-13 00 03 00
Difference:  0:02:00
m 2631391   2020-12-20 00 01 00
- 2631391   2020-12-20 00 03 00
Difference:  0:02:00
m 2641471   2020-12-27 00 02 00
- 2641471   2020-12-27 00 05 00
Difference:  0:03:00
m 2650109   2021-01-02 00 02 00
- 2650109   2021-01-02 00 04 00
Difference:  0:02:00
m 2651550   2021-01-03 00 04 00
- 2651550   2021-01-03 00 06 00
Difference:  0:02:00
m 2661627   2021-01-10 00 02 00
- 2661627   2021-01-10 00 04 00
Difference:  0:02:00
m 2665946   2021-01-13 00 02 00
- 2665946   2021-01-13 00 04 00
Difference:  0:02:00
m 2671705   2021-01-17 00 02 00
- 2671705   2021-01-17 00 05 00
Difference:  0:03:00
m 2681784   2021-01-24 00 03 00
- 2681784   2021-01-24 00 05 00
Difference:  0:02:00
m 2691863   2021-01-31 00 03 00
- 2691863   2021-01-31 00 06 00
Difference:  0:03:00
m 2701940   2021-02-07 00 02 00
- 2701940   2021-02-07 00 07 00
Difference:  0:05:00
m 2712016   2021-02-14 00 02 00
- 2712016   2021-02-14 00 08 00
Difference:  0:06:00
m 2722091   2021-02-21 00 02 00
- 2722091   2021-02-21 00 04 00
Difference:  0:02:00
m 2732170   2021-02-28 00 02 00
- 2732170   2021-02-28 00 06 00
Difference:  0:04:00
m 2742248   2021-03-07 00 03 00
- 2742248   2021-03-07 00 06 00
Difference:  0:03:00
m 2772485   2021-03-28 00 02 00
- 2772485   2021-03-28 00 04 00
Difference:  0:02:00
m 2792645   2021-04-11 00 03 00
- 2792645   2021-04-11 00 08 00
Difference:  0:05:00
m 2802720   2021-04-18 00 02 00
- 2802720   2021-04-18 00 05 00
Difference:  0:03:00
m 2812798   2021-04-25 00 02 00
- 2812798   2021-04-25 00 04 00
Difference:  0:02:00
m 2828637   2021-05-06 00 02 00
- 2828637   2021-05-06 00 05 00
Difference:  0:03:00
m 2832955   2021-05-09 00 02 00
- 2832955   2021-05-09 00 05 00
Difference:  0:03:00
m 2843033   2021-05-16 00 02 00
- 2843033   2021-05-16 00 06 00
Difference:  0:04:00
m 2853110   2021-05-23 00 02 00
- 2853110   2021-05-23 00 07 00
Difference:  0:05:00
m 2863185   2021-05-30 00 01 00
- 2863185   2021-05-30 00 05 00
Difference:  0:04:00
m 2873262   2021-06-06 00 01 00
- 2873262   2021-06-06 00 04 00
Difference:  0:03:00
m 2883341   2021-06-13 00 02 00
- 2883341   2021-06-13 00 05 00
Difference:  0:03:00
m 2886218   2021-06-15 00 01 00
- 2886218   2021-06-15 00 03 00
Difference:  0:02:00
m 2887659   2021-06-16 00 03 00
- 2887659   2021-06-16 00 05 00
Difference:  0:02:00
m 2893416   2021-06-20 00 01 00
- 2893416   2021-06-20 00 04 00
Difference:  0:03:00
m 2899174   2021-06-24 00 01 00
- 2899174   2021-06-25 00 01 00
Difference:  1 day, 0:00:00
m 2902055   2021-06-27 00 01 00
- 2902055   2021-06-27 00 03 00
Difference:  0:02:00
m 2912134   2021-07-04 00 01 00
- 2912134   2021-07-04 00 03 00
Difference:  0:02:00
m 2922214   2021-07-11 00 02 00
- 2922214   2021-07-11 00 07 00
Difference:  0:05:00
m 2932292   2021-07-18 00 04 00
- 2932292   2021-07-18 00 11 00
Difference:  0:07:00
m 2942365   2021-07-25 00 03 00
- 2942365   2021-07-25 00 10 00
Difference:  0:07:00
m 2952440   2021-08-01 00 04 00
- 2952440   2021-08-01 00 10 00
Difference:  0:06:00
m 2962515   2021-08-08 00 04 00
- 2962515   2021-08-08 00 10 00
Difference:  0:06:00
m 2966830   2021-08-11 00 04 00
- 2966830   2021-08-11 00 10 00
Difference:  0:06:00
m 2972585   2021-08-15 00 04 00
- 2972585   2021-08-15 00 10 00
Difference:  0:06:00
m 2982660   2021-08-22 00 04 00
- 2982660   2021-08-22 00 09 00
Difference:  0:05:00
m 2992736   2021-08-29 00 04 00
- 2992736   2021-08-29 00 10 00
Difference:  0:06:00
m 3002811   2021-09-05 00 04 00
- 3002811   2021-09-05 00 09 00
Difference:  0:05:00
m 3012888   2021-09-12 00 05 00
- 3012888   2021-09-12 00 11 00
Difference:  0:06:00
m 3022962   2021-09-19 00 04 00
- 3022962   2021-09-19 00 10 00
Difference:  0:06:00
m 3030157   2021-09-24 00 04 00
- 3030157   2021-09-24 00 06 00
Difference:  0:02:00
m 3033037   2021-09-26 00 05 00
- 3033037   2021-09-26 00 11 00
Difference:  0:06:00
m 3043113   2021-10-03 00 06 00
- 3043113   2021-10-03 00 11 00
Difference:  0:05:00
m 3053187   2021-10-10 00 04 00
- 3053187   2021-10-10 00 14 00
Difference:  0:10:00
m 3058938   2021-10-14 00 04 00
- 3058938   2021-10-14 00 06 00
Difference:  0:02:00
done

In [75]:
MasterData.loc[1628988-10:1628988+10,]

,Unix Timestamp,Date,Symbol,Open,High,Low,Close,Volume
1628978,1542317280000,2018-11-15 21:28:00,BTCUSD,5442.01,5446.09,5442.01,5444.99,2.002091
1628979,1542317340000,2018-11-15 21:29:00,BTCUSD,5444.99,5444.99,5440.00,5440.00,13.225249
1628980,1542317400000,2018-11-15 21:30:00,BTCUSD,5440.00,5440.00,5430.00,5430.00,2.500000
1628981,1542317460000,2018-11-15 21:31:00,BTCUSD,5430.00,5430.00,5420.00,5425.26,2.622299
1628982,1542317520000,2018-11-15 21:32:00,BTCUSD,5425.26,5425.26,5420.00,5423.00,11.643909
1628983,1542317580000,2018-11-15 21:33:00,BTCUSD,5423.00,5423.00,5423.00,5423.00,0.000000
1628984,1542317640000,2018-11-15 21:34:00,BTCUSD,5423.00,5431.27,5421.00,5428.00,12.071318
1628985,1542317700000,2018-11-15 21:35:00,BTCUSD,5428.00,5428.00,5427.89,5427.90,1.241923
1628986,1542317760000,2018-11-15 21:36:00,BTCUSD,5427.90,5427.90,5427.90,5427.90,0.000000
1628987,1542317820000,2018-11-15 21:37:00,BTCUSD,5427.90,5427.90,5427.89,5427.89,0.000009
1628988,1544217660000,2018-12-07 21:21:00,BTCUSD,3345.67,3345.67,3334.74,3334.74,2.081900
1628989,1544217720000,2018-12-07 21:22:00,BTCUSD,3334.74,3340.69,3332.70,3339.07,5.884672
1628990,1544217780000,2018-12-07 21:23:00,BTCUSD,3339.07,3339.35,3339.07,3339.35,0.015918
1628991,1544217840000,2018-12-07 21:24:00,BTCUSD,3339.35,3340.69,3338.04,3340.69,0.080246
1628992,1544217900000,2018-12-07 21:25:00,BTCUSD,3340.69,3340.70,3340.69,3340.69,0.827748
1628993,1544217960000,2018-12-07 21:26:00,BTCUSD,3340.69,3340.70,3332.32,3332.33,10.239198
1628994,1544218020000,2018-12-07 21:27:00,BTCUSD,3332.33,3335.54,3332.01,3332.01,0.147923
1628995,1544218080000,2018-12-07 21:28:00,BTCUSD,3332.01,3332.01,3332.01,3332.01,0.149949
1628996,1544218140000,2018-12-07 21:29:00,BTCUSD,3332.01,3334.28,3332.01,3334.11,0.302703
1628997,1544218200000,2018-12-07 21:30:00,BTCUSD,3334.11,3336.87,3331.60,3335.63,1.036642
1628998,1544218260000,2018-12-07 21:31:00,BTCUSD,3335.63,3335.63,3335.62,3335.62,0.002546

In [87]:
# MasterData.loc[1628987,'Date']
# MasterData.loc[1628988,'Date']
last_date,last_time = MasterData.loc[1628987,'Date'].split(' ')
last_hour,last_mins, last_sec = last_time.split(':') 
last_year,last_month,last_day = last_date.split('-')

date,time = MasterData.loc[1628988,'Date'].split(' ')
hour, mins, sec = time.split(':')
year,month,day = date.split('-')

# datetime(year, month, day, hour, minute, second)
a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
c = b-a 
print('Difference: ', c)

Difference:  21 days, 23:44:00

In [110]:
dt = datetime.datetime(2018, 12, 7,21,30,0)
# b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
# 2018-12-07 21:30:00
timestamp = dt.replace(tzinfo=timezone.utc).timestamp()
print(int(timestamp* 1000))
print(1544218200000)
print(datetime.datetime.utcfromtimestamp(1544218200000/1000).strftime('%Y-%m-%d %H:%M:%S'))

1544218200000
1544218200000
2018-12-07 21:30:00

In [128]:
# 1483315200 , 2017-01-02 00:00:00
        
dt = datetime.datetime(2017, 1, 2,0,0,0)
# b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
# 2018-12-07 21:30:00
timestamp = dt.replace(tzinfo=timezone.utc).timestamp()
print(int(timestamp))
print(1483315200)
print(datetime.datetime.utcfromtimestamp(1483315200).strftime('%Y-%m-%d %H:%M:%S'))

1483315200
1483315200
2017-01-02 00:00:00

In [133]:
last_date,last_hour,last_mins,last_sec
for i in range(len(master_data_file1)) :
    
    date,time = master_data_file1.loc[i,'Date'].split(' ')
    hour, mins, sec = time.split(':') 
    if i !=0:
        if (mins == '00'):
            if (hour == '00'):
                if (last_hour != '23' and last_mins != 59):
                    print('m',i,' ',last_date,last_hour,last_mins, last_sec)
                    print('-',i,' ',date,hour,mins,sec)
                    last_year,last_month,last_day = last_date.split('-')
                    year,month,day = date.split('-')
                    a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
                    b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
                    c = b-a 
                    print('Difference: ', c)
                    
                    
            else : 
                if (int(last_hour) != (int(hour)-1) and last_mins != 59):
                    print('m',i,' ',last_date,last_hour,last_mins, last_sec)
                    print('-',i,' ',date,hour,mins,sec)
                    last_year,last_month,last_day = last_date.split('-')
                    year,month,day = date.split('-')
                    a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
                    b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
                    c = b-a 
                    print('Difference: ', c)
        else: 
            if (int(last_mins) != int(mins)-1):
                print('m',i,' ',last_date,last_hour,last_mins, last_sec)
                print('-',i,' ',date,hour,mins,sec)
                last_year,last_month,last_day = last_date.split('-')
                year,month,day = date.split('-')
                a = datetime.datetime(int(last_year),int(last_month),int(last_day),int(last_hour),int(last_mins),int(last_sec))
                b = datetime.datetime(int(year),int(month),int(day),int(hour),int(mins),int(sec))
                c = b-a 
                print('Difference: ', c)
    last_date=date
    last_hour=hour
    last_mins=mins
    last_sec =sec
#     if i %1000000==0:
#         print('working')
print('done')

m 524160   2017-12-31 23 59 00
- 524160   2018-01-01 00 01 00
Difference:  0:02:00
m 1049759   2018-12-31 23 59 00
- 1049759   2019-01-01 00 01 00
Difference:  0:02:00
m 1575358   2019-12-31 23 59 00
- 1575358   2020-01-01 00 01 00
Difference:  0:02:00
m 2046272   2020-11-23 00 34 00
- 2046272   2020-11-23 00 36 00
Difference:  0:02:00
m 2046273   2020-11-23 00 36 00
- 2046273   2020-12-20 07 53 00
Difference:  27 days, 7:17:00
m 2063080   2020-12-31 23 59 00
- 2063080   2021-01-01 00 01 00
Difference:  0:02:00
done